import type { Metadata } from "next";
import Link from "next/link";
import ScrollFade from "../components/ScrollFade";

export const metadata: Metadata = {
 title: "Legal & Copyright | LATOM Wellness",
 description:
 "Copyright notice, DMCA takedown procedures, trademark information, and prohibited use policy for LATOM Wellness, PLLC.",
};

export default function LegalPage() {
 return (
 <div className="pt-28 pb-24 max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
 <div className="mb-10">
 <Link href="/" className="text-accent text-sm hover:underline">
 &larr; Back to Home
 </Link>
 </div>

 <ScrollFade>
 <h1 className="font-serif text-4xl font-bold text-ink mb-2">
 Legal &amp; Copyright
 </h1>
 <p className="text-faint text-sm mb-10">
 Effective: January 1, 2026 &mdash; LATOM Wellness, PLLC
 </p>
 </ScrollFade>

 <div className="space-y-10">

 {/* Copyright Notice */}
 <ScrollFade delay={50}>
 <section className="border border-line rounded-lg p-6 bg-bg">
 <h2 className="font-serif text-xl font-bold text-accent mb-3">
 Copyright Notice
 </h2>
 <p className="text-muted text-sm leading-relaxed">
 All content on this website, including but not limited to wellness protocols,
 dosing calculators, peptide databases, dosing tables, lab interpretation
 templates, treatment frameworks, educational guides, and written copy, is
 copyright &copy; 2026 LATOM Wellness, PLLC. All Rights Reserved.
 </p>
 <p className="text-muted text-sm leading-relaxed mt-3">
 Unauthorized reproduction, distribution, modification, public display,
 or creation of derivative works is prohibited without prior written
 permission from LATOM Wellness, PLLC.
 </p>
 </section>
 </ScrollFade>

 {/* No AI Training License */}
 <ScrollFade delay={100}>
 <section className="border border-line rounded-lg p-6 bg-bg">
 <h2 className="font-serif text-xl font-bold text-accent mb-3">
 No AI Training License
 </h2>
 <p className="text-muted text-sm leading-relaxed">
 No license, express or implied, is granted to use any content from this
 website for the purpose of training, fine-tuning, evaluating, or otherwise
 developing artificial intelligence models, large language models (LLMs),
 generative AI systems, machine learning datasets, or similar automated
 systems.
 </p>
 <p className="text-muted text-sm leading-relaxed mt-3">
 This prohibition applies to all content in any form, including text,
 structured data, tables, calculators, protocol logic, and any output
 generated by tools on this site. This site signals its opt-out status
 via <code className="text-accent text-xs">robots.txt</code> and
 HTTP response headers. Any scraping, crawling, or ingestion of this
 content for AI training purposes constitutes copyright infringement
 and breach of these terms.
 </p>
 </section>
 </ScrollFade>

 {/* Trademark Notice */}
 <ScrollFade delay={150}>
 <section className="border border-line rounded-lg p-6 bg-bg">
 <h2 className="font-serif text-xl font-bold text-accent mb-3">
 Trademark Notice
 </h2>
 <p className="text-muted text-sm leading-relaxed">
 &ldquo;LATOM Wellness&rdquo; and the LATOM Wellness logo are trademarks of
 LATOM Wellness, PLLC. Use of these marks without prior written authorization
 is strictly prohibited. Nothing on this site grants any license to use
 any trademark, trade name, or service mark of LATOM Wellness, PLLC.
 </p>
 </section>
 </ScrollFade>

 {/* Prohibited Use */}
 <ScrollFade delay={200}>
 <section className="border border-line rounded-lg p-6 bg-bg">
 <h2 className="font-serif text-xl font-bold text-accent mb-3">
 Prohibited Uses
 </h2>
 <p className="text-muted text-sm leading-relaxed mb-3">
 The following uses of this website and its content are expressly prohibited:
 </p>
 <ul className="text-muted text-sm leading-relaxed space-y-2 list-none">
 {[
 "Scraping or automated extraction of any content, data, or structured information",
 "Framing or inline linking to pages or content on this site",
 "Harvesting content for AI training, fine-tuning, or dataset creation",
 "Commercial reproduction or redistribution without written consent",
 "Systematic downloading of protocols, dosing tables, or calculator outputs",
 "Mirroring, caching, or archiving content for competitive purposes",
 ].map((item) => (
 <li key={item} className="flex gap-2">
 <span className="text-accent mt-0.5">&bull;</span>
 <span>{item}</span>
 </li>
 ))}
 </ul>
 </section>
 </ScrollFade>

 {/* DMCA Takedown */}
 <ScrollFade delay={250}>
 <section className="border border-line rounded-lg p-6 bg-bg">
 <h2 className="font-serif text-xl font-bold text-accent mb-3">
 DMCA Takedown Policy
 </h2>
 <p className="text-muted text-sm leading-relaxed">
 LATOM Wellness, PLLC complies with the Digital Millennium Copyright Act
 (17 U.S.C. &sect; 512). If you believe that content on this site infringes
 your copyright, or if you are the rights holder reporting infringement
 of LATOM Wellness content elsewhere, send a written notice to our
 designated Copyright Agent containing the information required by
 17 U.S.C. &sect; 512(c)(3):
 </p>
 <ul className="text-muted text-sm leading-relaxed space-y-1 mt-4 list-none">
 {[
 "A physical or electronic signature of the authorized person acting on behalf of the copyright owner",
 "Identification of the copyrighted work claimed to have been infringed",
 "Identification of the allegedly infringing material and its location on the web",
 "Your contact information (address, telephone, email)",
 "A statement of good faith belief that the disputed use is not authorized",
 "A statement under penalty of perjury that the information is accurate and you are authorized to act",
 ].map((item) => (
 <li key={item} className="flex gap-2">
 <span className="text-accent mt-0.5">&bull;</span>
 <span>{item}</span>
 </li>
 ))}
 </ul>
 <div className="mt-6 p-4 bg-[#0f0f14] border border-line rounded-md space-y-1">
 <p className="text-ink text-sm font-semibold">Designated Copyright Agent</p>
 <p className="text-muted text-sm">LATOM Wellness, PLLC</p>
 <p className="text-muted text-sm">
 Email:{" "}
 <a
 href="mailto:legal@latomwellness.com"
 className="text-accent hover:underline"
 >
 legal@latomwellness.com
 </a>
 </p>
 </div>
 <p className="text-faint text-xs leading-relaxed mt-4">
 Note: This contact is for copyright and DMCA matters only. For
 general inquiries, use{" "}
 <a
 href="mailto:info@latomwellness.com"
 className="text-accent hover:underline"
 >
 info@latomwellness.com
 </a>
 .
 </p>
 </section>
 </ScrollFade>

 {/* Medical Disclaimer */}
 <ScrollFade delay={300}>
 <section className="border border-line rounded-lg p-6 bg-bg">
 <h2 className="font-serif text-xl font-bold text-accent mb-3">
 Medical Disclaimer
 </h2>
 <p className="text-muted text-sm leading-relaxed">
 All content on this website, including protocols, dosing information,
 lab interpretation frameworks, and educational materials, is provided
 for informational and educational purposes only. It does not constitute
 medical advice, diagnosis, or treatment. No physician-patient relationship
 is created by accessing or using this site.
 </p>
 <p className="text-muted text-sm leading-relaxed mt-3">
 A formal physician-patient relationship is established only through
 explicit written consent following proper intake procedures with a
 licensed LATOM Wellness provider. Always consult a qualified healthcare
 provider before making any medical decisions. If you are experiencing
 a medical emergency, call 911 immediately.
 </p>
 </section>
 </ScrollFade>

 {/* Governing Law */}
 <ScrollFade delay={350}>
 <section className="border border-line rounded-lg p-6 bg-bg">
 <h2 className="font-serif text-xl font-bold text-accent mb-3">
 Governing Law &amp; Jurisdiction
 </h2>
 <p className="text-muted text-sm leading-relaxed">
 This notice and all matters arising from it are governed by the laws of
 the Commonwealth of Virginia, without regard to conflict-of-law principles.
 Any dispute shall be subject to the exclusive jurisdiction of the state
 and federal courts located in Henrico County, Virginia.
 </p>
 </section>
 </ScrollFade>

 </div>

 <ScrollFade delay={400}>
 <div className="mt-12 pt-8 border-t border-line text-center">
 <p className="text-faint text-xs">
 &copy; 2026 LATOM Wellness, PLLC. All Rights Reserved. Proprietary protocols
 &mdash; no AI training license granted.
 </p>
 <div className="mt-3 flex justify-center gap-6">
 <Link href="/terms" className="text-faint text-xs hover:text-accent transition-colors">
 Terms of Service
 </Link>
 <Link href="/privacy" className="text-faint text-xs hover:text-accent transition-colors">
 Privacy Policy
 </Link>
 </div>
 </div>
 </ScrollFade>
 </div>
 );
}
